name: prolance_app
description: "Prolance Freelancing Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  skeletonizer: ^2.1.3
  flutter_staggered_animations: ^1.1.1
  glassmorphism: ^3.0.0
  fl_chart: ^0.70.2
  super_tooltip: ^2.0.6
  flutter_expandable_fab: ^2.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  provider: ^6.1.2
  go_router: ^14.8.1
  animate_do: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^3.0.0
  image_picker: ^1.1.2
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  timeago: ^3.7.0
  badges: ^3.1.2
  shared_preferences: ^2.5.3
  file_picker: ^8.1.2
  file_saver: ^0.2.14
  animations: ^2.0.11
  http: ^1.2.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flex_color_scheme: ^8.4.0
  dynamic_color: ^1.8.1
  gap: ^3.0.1
  dotted_border: ^3.1.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  app_links: ^6.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  device_frame: ^1.1.0
  pdfx: ^2.6.0
  rive: ^0.13.12
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/rive/
    - assets/data/category_skills.json
    - assets/data/world_locations.json
