services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prolance
      POSTGRES_PASSWORD: prolance
      POSTGRES_DB: prolance
    ports:
      - "5432:5432"
    volumes:
      - prolance_pg:/var/lib/postgresql/data

volumes:
  prolance_pg:
